### ISSUE TITLE
Recursive processing

### ISSUE THREAD

**Issue by GurovDmitriy** [thumbrise/srtor#5]
**Is your feature request related to a problem? Please describe.**
Most often when I use it, I have a nested folder structure that contains both video files and subtitles for them. After translating subtitles, I usually save the original subtitle files in a separate folder or archive and replace the current ones with the translated files.

**Describe the solution you'd like**
Automatically search relative to the root directory, search for subtitles, translate them, save original files, replace current files with translated files.

**Comment by thumbrise** [comment]
@GurovDmitriy 
You want to add an extra interactive steps:
1. Translate directories recursively?
2. Replace original subtitles?
3. If 2 is positive, then Archive the original subtitles?

Is it right?

**Comment by GurovDmitriy** [comment]
I think the simpler the more convenient, whether to hide the original in a folder and replace the files, it seems to me that you need to decide by default, give the user only a minimum of settings

**Comment by thumbrise** [comment]
> it seems to me that you need to decide by default

@GurovDmitriy I'm not sure that all users want this non-obvious default behavior. If the program manipulates the user's original files in any way _without their consent_, it may _anger_ them

I agree that a large number of options can complicate this simple program, but I don't agree with this default behavior
